#!/usr/bin/env bash
sudo cp 49-teensy.rules /etc/udev/rules.d/

ROSDISTRO="$(rosversion -d)"
BASE=$1
SENSOR=$2

echo "
______ _____________   _________ ________ _______ ________ _______ ________
___  / ____  _/___  | / /__  __ \___  __ \__  __ \___  __ )__  __ \___  __/
__  /   __  /  __   |/ / _  / / /__  /_/ /_  / / /__  __  |_  / / /__  /   
_  /_____/ /   _  /|  /  / /_/ / _  _, _/ / /_/ / _  /_/ / / /_/ / _  /    
/_____//___/   /_/ |_/   \____/  /_/ |_|  \____/  /_____/  \____/  /_/     
                    
                            http://linorobot.org                                                                          
"
if [ "$3" != "test" ]
    then
        if [ "$*" == "" ]
            then
                echo "No arguments provided"
                echo
                echo "Example: $ ./install.sh 2wd xv11"
                echo
                exit 1
                
        elif [[ "$1" != "2wd" && "$1" != "4wd" && "$1" != "mecanum" && "$1" != "ackermann" ]]
            then
                echo "Invalid linorobot base: $1"
                echo
                echo "Valid Options:"
                echo "2wd"
                echo "4wd"
                echo "ackermann"
                echo "mecanum"
                echo
                exit 1

        elif [[ "$2" != "xv11" && "$2" != "rplidar" ]]
            then
                echo "Invalid linorobot sensor: $2. Setting to default: xv11"
                LIDAR=xv11
        fi


        echo
        echo -n "You are installing ROS-$ROSDISTRO Linorobot for $BASE base with a $SENSOR sensor. Enter [y] to continue. " 
        read reply
        if [[ "$reply" != "y" && "$reply" != "Y" ]]
            then
                echo "Wrong input. Exiting now"
                exit 1
        fi
fi

echo
echo "INSTALLING NOW...."
echo

sudo apt-get update
sudo apt-get install -y avahi-daemon
sudo apt-get install -y openssh-server
sudo apt-get install -y python-setuptools 
sudo apt-get install -y python-dev 
sudo apt-get install -y build-essential
sudo apt-get install -y python-gudev

sudo easy_install pip
sudo pip install -U platformio
sudo rm -rf ~/.platformio/

sudo apt-get install -y ros-$ROSDISTRO-roslint
sudo apt-get install -y ros-$ROSDISTRO-rosserial
sudo apt-get install -y ros-$ROSDISTRO-imu-filter-madgwick
sudo apt-get install -y ros-$ROSDISTRO-gmapping
sudo apt-get install -y ros-$ROSDISTRO-map-server
sudo apt-get install -y ros-$ROSDISTRO-navigation

if [ "$SENSOR" == "xv11" || "$3" == "test" ]
    then
        sudo apt-get install -y ros-$ROSDISTRO-xv-11-laser-driver
fi

if [ "$BASE" == "ackermann" ]
    then
        sudo apt-get install -y ros-$ROSDISTRO-teb-local-planner
fi

cd 
mkdir -p linorobot_ws/src
cd linorobot_ws/src
catkin_init_workspace

git clone https://github.com/linorobot/lino_msgs.git
cd ~/linorobot_ws
catkin_make

echo "source ~/linorobot_ws/devel/setup.bash" >> ~/.bashrc
source ~/.bashrc

cd src
git clone https://github.com/linorobot/lino_pid.git
git clone https://github.com/grassjelly/linorobot.git
git clone https://github.com/linorobot/imu_calib.git

if [ "$SENSOR" == "rplidar" || "$3" == "test" ]
    then
        https://github.com/robopeak/rplidar_ros.git
fi

cd linorobot
TRAVIS_BRANCH="$(TRAVIS_BRANCH)"
if [ "$TRAVIS_BRANCH" = "devel" ]; then git checkout devel; fi
git checkout devel

cd teensy/firmware
export PLATFORMIO_CI_SRC=$PWD/src/firmware.ino
platformio ci --project-conf=./platformio.ini --lib="./lib/ros_lib" --lib="./lib/config"  --lib="./lib/motor"  --lib="./lib/kinematics"  --lib="./lib/pid"  --lib="./lib/imu"

cd ~/linorobot_ws
catkin_make

echo
echo "INSTALLATION DONE!"
echo